### ISSUE TITLE
When in a locked account plan, a subgroup has set as ‘skubelongruppe’, when you add subegoupr the application crashes.

### ISSUE THREAD

**Issue by TabtIrummet** [Difference/LCCbygBase#113] opened 2017-10-05 10:05 UTC
The most of the times, not always, on the account plan if you select the ‘skubelongruppe’ for a subgroup (in any account plan) and then you lock the tab, when you are going to add or delete subgroup in the locked tab the application crashes. For example in Main Project template (In Danish or English version) in Management tab, select the ‘skubelongruppe’ for the ‘insurance’ subgroup and then lock the template. If you try to add a new subgroub by using the arrows of the ‘insurance’ subgroup then the application crashes and is forced to shut down.

**Comment by Difference** [comment] 2017-10-05 12:58
Confirmed in v.2.2.24. 
Closing this, because it was fixed together with issue#110

**Closed by Difference** 2017-10-05 12:58 UTC
